### ISSUE TITLE
Flames

### ISSUE THREAD

**Issue by zconn** [dancornutt/Porsche944#1]
Generally it seems to be fine, but I didn't see anywhere in your breakdown you were going to do a sweet paint job includes flames coming up from the tires or at least just across the side. Is that something just missing from the documentation? or have some other ground effects ideas for the final build?

**Comment by dancornutt** [comment]
The original color is red so we plan on sanding off the shitty black paint in strategic areas to produce original paint schemes such as said flames. Aesthetic "upgrades" will be of prime focus at a TBD specified date.
